#!/usr/bin/env node
/**
 * Reads .env and generates js/env-config.js
 * Usage: node scripts/generate-env.js
 */
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, "..", ".env");
const outPath = path.join(__dirname, "..", "js", "env-config.js");

if (!fs.existsSync(envPath)) {
  console.error("Error: .env file not found.");
  console.error("Copy .env.example to .env and fill in your values:");
  console.error("  cp .env.example .env");
  process.exit(1);
}

const lines = fs.readFileSync(envPath, "utf-8").split("\n");
const vars = {};

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const eqIdx = trimmed.indexOf("=");
  if (eqIdx === -1) continue;
  const key = trimmed.slice(0, eqIdx).trim();
  const val = trimmed.slice(eqIdx + 1).trim();
  vars[key] = val;
}

const output = `/* =========================================================
   AUTO-GENERATED by: npm run env
   DO NOT EDIT — source values in .env
   ========================================================= */
window.LV_ENV = ${JSON.stringify(vars, null, 2)};
`;

fs.writeFileSync(outPath, output, "utf-8");
console.log("Generated js/env-config.js with", Object.keys(vars).length, "variables.");
