#!/usr/bin/env node
/**
 * Reads .env (or process.env on Cloudflare Pages) and generates js/env-config.js
 * Usage: node scripts/generate-env.js
 */
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, "..", ".env");
const outPath = path.join(__dirname, "..", "js", "env-config.js");

const VITE_KEYS = [
  "VITE_SUPABASE_URL",
  "VITE_SUPABASE_ANON_KEY",
  "VITE_SUPABASE_TABLE"
];

const vars = {};

if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (VITE_KEYS.includes(key)) {
      vars[key] = val;
    }
  }
  console.log("Read", Object.keys(vars).length, "public variables from .env (secrets excluded)");
} else {
  console.log("No .env file found — falling back to process.env (Cloudflare Pages build)");
  for (const key of VITE_KEYS) {
    if (process.env[key]) {
      vars[key] = process.env[key];
    }
  }
  if (Object.keys(vars).length === 0) {
    console.error("Error: No env variables found in .env or process.env.");
    process.exit(1);
  }
}

const output = `/* =========================================================
   AUTO-GENERATED by: npm run env
   DO NOT EDIT — source values in .env or Cloudflare Pages env vars
   ========================================================= */
window.LV_ENV = ${JSON.stringify(vars, null, 2)};
`;

fs.writeFileSync(outPath, output, "utf-8");
console.log("Generated js/env-config.js with", Object.keys(vars).length, "variables.");
